#### <center> Module 4b - Asymmetric Cryptographic Primitives
## <center> SYSE 549: Secure Vehicle and Industrial Networking
## <center> <img src="https://www.engr.colostate.edu/~jdaily/Systems-EN-CSU-1-C357.svg" width="400" />
### <center> Instructor: Dr. Jeremy Daily

## Learning Objectives

By the end of this notebook you should be able to:

1. **Generate** an RSA key pair and explain what each half is for and where each half may travel.
2. **Serialize** a public key to PEM and load one from PEM, which is how keys actually move between systems.
3. **Encrypt** a short message with a recipient's public key using OAEP padding, and explain why textbook RSA is unusable without padding.
4. **Predict** the maximum message length RSA can encrypt for a given key size, and show what happens when you exceed it.
5. **Build** an envelope-encryption message: a symmetric key protected by RSA, wrapping a payload of any length.
6. **Trace** each step to [FIPS 186-5](https://csrc.nist.gov/pubs/fips/186-5/final), [RFC 8017](https://www.rfc-editor.org/rfc/rfc8017) (PKCS#1 v2.2), and NIST [SP 800-56B](https://csrc.nist.gov/pubs/sp/800/56/b/r2/final) / SP 800-57.

## Acronyms used in this notebook

| Acronym | Expansion | One-line meaning |
|---|---|---|
| **RSA** | Rivest-Shamir-Adleman | The public-key algorithm this notebook is built on |
| **OAEP** | Optimal Asymmetric Encryption Padding | The mandatory padding for RSA encryption |
| **MGF1** | Mask Generation Function 1 | A helper hash construction used inside OAEP |
| **AES** | Advanced Encryption Standard | The symmetric block cipher used for bulk data |
| **AEAD** | Authenticated Encryption with Associated Data | A cipher that also proves the data is unmodified |
| **GCM** | Galois/Counter Mode | The usual AEAD mode for AES |
| **PEM** | Privacy-Enhanced Mail | The `-----BEGIN ...-----` text format keys travel in |
| **DER** | Distinguished Encoding Rules | The binary encoding that PEM wraps in base64 |
| **ASN.1** | Abstract Syntax Notation One | The schema language describing what is inside a key |
| **PKCS** | Public-Key Cryptography Standards | Where RSA's formats and padding come from |
| **DEK** | Data Encryption Key | The throwaway symmetric key that protects one message |
| **KEK** | Key Encryption Key | The long-lived key that protects a DEK |
| **KEM** | Key Encapsulation Mechanism | A modern replacement for "encrypt a random key" |
| **KDF** | Key Derivation Function | Turns one secret into usable key material |
| **HPKE** | Hybrid Public Key Encryption | The standardized version of the pattern built here |
| **TLS** | Transport Layer Security | The protocol behind HTTPS |
| **PKI** | Public Key Infrastructure | The system that says whose key is whose |
| **FIPS** | Federal Information Processing Standard | A US government standard |

## The problem asymmetric cryptography solves

Symmetric cryptography needs both parties to already share a secret key. That is a fine
assumption for two programs written by the same team, or two controllers built on the same
production line. It falls apart everywhere else:

* Your browser has never met the server it is about to load a page from, and must agree on
  a key before the first byte of the request.
* A backup archive is encrypted today and opened in five years by a different administrator.
* A software update is signed once and distributed to two hundred thousand machines that
  have no channel back to the publisher.
* A technician's laptop connects to equipment owned by someone else.

Asymmetric -- or **public-key** -- cryptography splits the key in two:

* a **private key** that never leaves the machine that generated it, and
* a **public key** that you can print on a billboard.

Anything encrypted with the public key can only be opened with the private key. That one
asymmetry is enough to bootstrap everything else.

| | Symmetric | Asymmetric (public-key) |
|---|---|---|
| Keys | one shared secret | a key pair per party |
| Keys needed for $n$ parties | $n(n-1)/2$ | $n$ |
| Speed | ~1 GB/s with hardware AES | roughly a thousand times slower |
| Max message | unlimited | a few hundred bytes |
| Solves | bulk confidentiality | key distribution and identity |

They are not competitors. Real systems use asymmetric cryptography to move a symmetric key,
then symmetric cryptography to move the data. That pattern is called **envelope
encryption**, and it is the second half of this notebook.

> **Standards trace.** RSA key generation and use is specified in **FIPS 186-5** and
> **RFC 8017** (PKCS #1 v2.2). Key-establishment schemes using RSA are in **NIST SP 800-56B
> Rev. 2**. Key sizes and their expected lifetimes are in **[SP 800-57 Part 1 Rev. 5](https://csrc.nist.gov/pubs/sp/800/57/pt1/r5/final)**;
> **[SP 800-131A Rev. 2](https://csrc.nist.gov/pubs/sp/800/131/a/r2/final)** sets the current floor at **2048 bits**. The draft
> **[NIST IR 8547](https://csrc.nist.gov/pubs/ir/8547/ipd)** (initial public draft, Nov. 2024) proposes deprecating RSA after
> 2030 and disallowing it after 2035 in favor of post-quantum algorithms.

In [1]:
# One-time setup. Version 41 or higher is assumed; restart the kernel if pip installs.
%pip install --upgrade cryptography

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ------------------------ --------------- 2.4/3.8 MB 29.1 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 34.4 MB/s  0:00:00
  Attempting uninstall: cryptography
    Found existing installation: cryptography 48.0.0
    Uninstalling cryptography-48.0.0:
      Successfully uninstalled cryptography-48.0.0
Note: you may need to restart the kernel to use updated packages.


  You can safely remove it manually.


In [2]:
# Sanity check before class. All four notebooks in module 04 need this to succeed.
import cryptography
print("cryptography", cryptography.__version__)

cryptography 50.0.1


## Proposition: 

### Confidentiality
Alice would like to send a message to Bob such that only Bob can read it.

Bob sends Alice his public key. He doesn't care if anyone else can read it. 

Alice uses Bob's public key to encrypt data and send it back to Bob.

Bob decrypts the data with his private key. 

<img src="Asymmetric Encryption Primitives - Send Secret Message.svg"/> 



Let's work out these scenarios with some code. We'll use the RSA asymmetric key for this example.

In [ ]:
# rsa            -> key generation and the RSA primitive itself
# serialization  -> converting key objects to/from PEM and DER byte formats
# hashes         -> SHA-256, used inside the OAEP padding scheme
# padding        -> OAEP (Optimal Asymmetric Encryption Padding). This is padding for
#                   public-key encryption, and is unrelated to the PKCS#7 block padding
#                   used with symmetric block ciphers.
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/

## Generate Keys for Alice

In [4]:
# Key generation searches for two large random primes, so it is SLOW (~0.1-2 s)
# and it consumes real entropy. Generate a key once and store it; never per message.
private_key_for_alice = rsa.generate_private_key(
                         public_exponent=65537,  # F4: standard, fast, and safe. Do not change it.
                         key_size=2048           # SP 800-131A floor; 3072+ for anything long-lived
                        )
private_key_for_alice

In [5]:
# A key object lives in memory. To store or transmit it you must SERIALIZE it.
# PEM = base64 of the DER encoding, wrapped in ----BEGIN/END---- lines, so it is email-safe.
private_pem_for_alice = private_key_for_alice.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    # NoEncryption() writes the private key in the clear -- fine for a classroom,
    # never for a real device. Use BestAvailableEncryption(passphrase) instead.
    encryption_algorithm=serialization.NoEncryption()
 )
print(private_pem_for_alice.decode('ascii'))

-----BEGIN RSA PRIVATE KEY-----
MIIEoQIBAAKCAQEAuX+KTYrZ0Fr3KVJLoq/K0YGqojC8IjPI7uGnEkuJixkSA2tn
cbcu9xzgBIXs94/EZ/ErRsmQKpI3hIN+YhVp8J5NtD7I8u0rTJqJPCKhftjrlVRO
wXnOIq7U+iBXnQ3a2YNFD6n69lz2saV5P5Iyl33r7X57Ox/7RasjElu9i5txAtxw
t1wiZPLMfsDyTktE87ptl9LIevumSdCWAQFAufm823wm7Cyi+cUklY1RsajR8Dao
4pvtw1htDxdH05cuiJwCIpqGc0wmexJMFi7u2qv41zShVhRvvKOPw5tgeSoI8R2o
yzik4t+qaxlaKeGFLo03e8WReQYKqLzFUhvk/wIDAQABAoH/JSvppKBIBZI09Sxu
+6rYE1bO9EsDAdeR7EyyFHh0/eq7ZI2hRqhVDclutEYiHKz/YdTYinBzWa4mceeB
UlmRx4xX0q0ol4WI2uqDLzz0hinx2EeMs9I0yVgMVay/FQaYITF5vvad08CaFTJg
ZnZlecLbndVt3FGl7wNCtx5Ew85Wve8szOJsKJYwaYrlunBFNgoHL2YKssk8QWeq
8CkmRbCt2zMVS0jD+vP/80V0mb+IORTwG1Gf/P+5awwWsfCkQajHAbYkvZRemBSo
bRVVX37sMfS4EoZ85BTfrCmWSbZbzEBp24WFN225hiFdGtjl66ShEd7sZQUKXKrL
Oq61AoGBAP6lcuqJrvo109LBEnzLbRgZyBZt5qQrBXAjrQU7mMWaweFO6nmiJWSQ
n4RR9XsEicwDQ+2f8UTk2b78LlL+J82D+t+klF1b7BdaLmxz0FgVEtulaL3VTuml
v7NOqOb8D2sucnVjh41W5IwDyHjElePlYTIt4vStCGIX9DlsiqVlAoGBALp7/Kbw
/2HbPS2lEjdHTfa1eGIFXEnBGfkPe0czDTiWSZD2eAelA3P7xGpaMYJ7M1

In [27]:
# The public key is DERIVED from the private key -- it is not a separate secret.
# This is why losing a private key loses the identity, but publishing the public one costs nothing.
public_key_for_alice = private_key_for_alice.public_key()
public_key_for_alice

In [28]:
# SubjectPublicKeyInfo is the standard public-key wrapper (RFC 5280); it names the
# algorithm alongside the key, so the receiver knows what it is holding.
public_pem_key_for_alice = public_key_for_alice.public_bytes(
       encoding=serialization.Encoding.PEM,
       format=serialization.PublicFormat.SubjectPublicKeyInfo
)
print(public_pem_key_for_alice.decode('ascii'))

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuX+KTYrZ0Fr3KVJLoq/K
0YGqojC8IjPI7uGnEkuJixkSA2tncbcu9xzgBIXs94/EZ/ErRsmQKpI3hIN+YhVp
8J5NtD7I8u0rTJqJPCKhftjrlVROwXnOIq7U+iBXnQ3a2YNFD6n69lz2saV5P5Iy
l33r7X57Ox/7RasjElu9i5txAtxwt1wiZPLMfsDyTktE87ptl9LIevumSdCWAQFA
ufm823wm7Cyi+cUklY1RsajR8Dao4pvtw1htDxdH05cuiJwCIpqGc0wmexJMFi7u
2qv41zShVhRvvKOPw5tgeSoI8R2oyzik4t+qaxlaKeGFLo03e8WReQYKqLzFUhvk
/wIDAQAB
-----END PUBLIC KEY-----



## Generate Keys for Bob

In [29]:
# Bob generates his own keypair independently -- there is no shared setup step at all.
private_key_for_bob = rsa.generate_private_key(
                         public_exponent=65537,
                         key_size=2048 # should use at least 3072 for long-lived keys
                        )
private_key_for_bob

In [30]:
# Same serialization as Alice's. Note that an RSA private key file contains p, q, d
# and the CRT parameters -- an attacker who reads this file owns Bob's identity.
private_pem_for_bob = private_key_for_bob.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=serialization.NoEncryption()
 )
print(private_pem_for_bob.decode('ascii'))

-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAqcmncp5nK6qvvlt7kzoT3C3CD9p/ncUt6KZLs/kFxiSgcg3q
1AcozLFAg4J+14VhIseAA5rn1yrUCaHnyOkOvLGVND1YsHajV8WuUSbWKQx03QUt
3GshZAKsBxoVw5MCP57IXNSYPqOFsh+TwOC1bKIGVf8vVDQ/uC+1X3/juhUU5hKs
Dgy+Tb86bVbldKkcPU7K+a0aP0pu6FQ4E0F0sukF7SvzcqT6pX12k6YDUKi1xhdJ
asugtnbtaRqiQ/UGPJrqmu74CneBGjycqkOY60I/7WdGbXbF9d3bCnSehA7+Z9Wz
zJ/dJZhgbsDDcPIV14M894jNUYPa0dHP39ErgQIDAQABAoIBACSiJA0ktM105Tjc
+7d7KTRRMiUiB3VmyR5AnSZedTq4hd699nwbdFff6bPGSPBe8KOkqE/+0QV5kejn
JD/S2zFm3nK4RsXCP0GNnywWxU/zhlZ2ytubSMfPlMbuf6IkOrC35XK0Ewo21X6m
dgaAZVykQ9oztkZEhLgMoSVTDnNERVMsPqEl8NHkqnMX73ecJptU+x8ZXNR52u1k
u2Ld47UNHxAlzd2QmAneid2v5MTMYjjy8/vnAj5fkrCMxxJxpuJZDIQ4F65bazBR
D9hT9y8j5PgS/xuhRICIVIRcjSULFsCPmcbGM7SPteZBpF/uLWFaIcipuHVJ7/Sl
bZZkZ80CgYEA5OtZPbSGW7/8+ihF3dmJDWzEYFSbgiPu5CVFFEZNKzOjfB4KU7Fr
pJJwCSVICWQkPCdhIeHrhYc1rH85uZcwuO4rfVMyglt+gWcLfKL6xFI1uTCzuvbJ
TugzK5JS6EXTpZbxVjHUXJp9Qnqd60zvtDVhjn7jHnlXzn+lquf1QC0CgYEAvd+M
Z5N67z7iCBQIcU/YX9Kky6MsLoL7x+VVEmaJmMpuL15VqQR8pEyouhE4VW

In [31]:
# Bob derives his public key the same way Alice did.
public_key_for_bob = private_key_for_bob.public_key()
public_key_for_bob

In [32]:
# This block is what Bob publishes. Compare its length to the private PEM above --
# the public key is roughly a quarter the size, because it is only (n, e).
public_pem_key_for_bob = public_key_for_bob.public_bytes(
       encoding=serialization.Encoding.PEM,
       format=serialization.PublicFormat.SubjectPublicKeyInfo
)
print(public_pem_key_for_bob.decode('ascii'))

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqcmncp5nK6qvvlt7kzoT
3C3CD9p/ncUt6KZLs/kFxiSgcg3q1AcozLFAg4J+14VhIseAA5rn1yrUCaHnyOkO
vLGVND1YsHajV8WuUSbWKQx03QUt3GshZAKsBxoVw5MCP57IXNSYPqOFsh+TwOC1
bKIGVf8vVDQ/uC+1X3/juhUU5hKsDgy+Tb86bVbldKkcPU7K+a0aP0pu6FQ4E0F0
sukF7SvzcqT6pX12k6YDUKi1xhdJasugtnbtaRqiQ/UGPJrqmu74CneBGjycqkOY
60I/7WdGbXbF9d3bCnSehA7+Z9WzzJ/dJZhgbsDDcPIV14M894jNUYPa0dHP39Er
gQIDAQAB
-----END PUBLIC KEY-----



> **What is actually inside an RSA key?** The public key is the pair $(n, e)$, where
> $n = pq$ for two large secret primes and $e = 65537$. The private key is $d$, the
> inverse of $e$ modulo $\lambda(n)$. Encryption is $c = m^e \bmod n$ and decryption is
> $m = c^d \bmod n$. Its security rests on the belief that factoring $n$ is hard -- a
> belief that Shor's algorithm invalidates on a sufficiently large quantum computer,
> which is why the draft [NIST IR 8547](https://csrc.nist.gov/pubs/ir/8547/ipd) proposes an expiry date for RSA. You can look at the raw numbers
> with `.private_numbers()` and `.public_numbers()`.

In [33]:
# Peek at the actual integers. n is 2048 bits; e is the small public exponent.
nums = public_key_for_bob.public_numbers()
print("public exponent e =", nums.e)
print("modulus n has", nums.n.bit_length(), "bits and starts", hex(nums.n)[:34], "...")

# The maximum plaintext RSA-OAEP can carry, from RFC 8017 Sec. 7.1.1:
#   k - 2*hLen - 2  where k = modulus bytes and hLen = hash output bytes
k, hLen = private_key_for_bob.key_size // 8, 32   # 256 bytes, SHA-256
print(f"\nOAEP-SHA256 max message for a {private_key_for_bob.key_size}-bit key: {k - 2*hLen - 2} bytes")

public exponent e = 65537
modulus n has 2048 bits and starts 0xa9c9a7729e672baaafbe5b7b933a13dc ...

OAEP-SHA256 max message for a 2048-bit key: 190 bytes


## Alice Sends a Message to Bob

In [34]:
# The message Alice wants only Bob to read. Note it is bytes, not str.
plain_text = b'We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard;'
print(len(plain_text), "bytes")
plain_text

121 bytes


b'We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard;'

In [ ]:
# This is all Alice has of Bob: a block of public text she could have pulled off a
# web page. Nothing secret has been exchanged. (Whether it is REALLY Bob's key is the
# unanswered question that digital signatures and certificates exist to solve.)
public_pem_key_for_bob

In [36]:
# PEM bytes are just text; load_pem_public_key parses them into a usable key object.
encryption_key = serialization.load_pem_public_key(public_pem_key_for_bob)
encryption_key

In [37]:
# OAEP (Optimal Asymmetric Encryption Padding) is mandatory, not optional.
# Textbook RSA -- m^e mod n with no padding -- is deterministic and malleable:
# the same message always gives the same ciphertext, and c1*c2 decrypts to m1*m2.
# OAEP injects randomness and structure, so encrypting twice gives different results.
cipher_text_from_alice = encryption_key.encrypt(
     plain_text,
     padding.OAEP(
         mgf=padding.MGF1(algorithm=hashes.SHA256()),  # mask generation function
         algorithm=hashes.SHA256(),                    # hash used inside OAEP
         label=None                                    # optional context string, rarely used
     )
 )
# Output is always exactly the modulus size: 2048 bits = 256 bytes, regardless of input.
print(len(cipher_text_from_alice), "bytes of ciphertext")
cipher_text_from_alice

256 bytes of ciphertext


b'\xa4\xcbW\xfb\xc9\xd7\x86(\xa1\x13\xd2o\xaf?`\xe8\xa4\x81\xd8\xaf\xde2m\xd5Y0S\xbe\xc5SW\xeew\xa2n`p\x07\xbb\xd7\xa3\xc9On\xa7\xcc\xffDM[\'K\xe1\x02\xc7\x0f\x85\xac\xf4m\x95N\xaa\x86\xf4\x04\xda8W\xa6\xb5\xe3\xce\x1eX1\x13\x9f\x04\xdaI\xed\x8e^\xb6Q\xf3\xc8\x01\xd6)\xdf\x86\xea2I\x0c\xb7\xff\xe8\x8c\xd9\x90\xae\\\xdaU\x90k\x81U/K\xceNy\x96\x1c\x0b\xf6\x9d\xf0G\xe8\xcb2fQ\x0f\xe5\xa8\xecE\xf70P$\xdd\x11\x8co\xf4\xf0\x8f\x0bH\xe7h\x0b\xcb\xb0,\x7f\x1baYs\xdf\x89\xd0\xa1\xeb\x1bt\x9aF\r\xe1=$\x837\xd7\x81\xf7\x14\x10c\xbc\xd0\xda\x86L\xfe~\n\x16e\xc2,\x17\x0b\xc8\x11]\xbd\x99]\xca\tI\xd3\x15\xf0\xc7dR}\xab\xa3\x04\xc2E\x97\xbc\xd0|^\xcb\x89\xaa\x06\xa8\xe3\xc1\x04\r\n\x98\xfcA\x0c\xda<Tt\x83h\xc4\xc0\xc6\xd3Bb\xf2\x1ar\x16\x0b\xc4"\xfak2\xfd\x1b'

In [38]:
# Run the same encryption again and compare -- OAEP randomizes every operation.
again = encryption_key.encrypt(plain_text, padding.OAEP(
    mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None))
print("Two encryptions of the SAME message are identical?", again == cipher_text_from_alice)
print("This is why textbook RSA leaks: without OAEP the answer would be True.")

Two encryptions of the SAME message are identical? False
This is why textbook RSA leaks: without OAEP the answer would be True.


In [39]:
# Raw ciphertext contains arbitrary bytes, including nulls, so it cannot go in
# an email body, a JSON field, or a URL until it is text-encoded.
import base64

In [40]:
# base64 costs 33% more bytes but makes the ciphertext safe for any text channel.
message_from_alice = base64.b64encode(cipher_text_from_alice)
message_from_alice

b'pMtX+8nXhiihE9Jvrz9g6KSB2K/eMm3VWTBTvsVTV+53om5gcAe716PJT26nzP9ETVsnS+ECxw+FrPRtlU6qhvQE2jhXprXjzh5YMROfBNpJ7Y5etlHzyAHWKd+G6jJJDLf/6IzZkK5c2lWQa4FVL0vOTnmWHAv2nfBH6MsyZlEP5ajsRfcwUCTdEYxv9PCPC0jnaAvLsCx/G2FZc9+J0KHrG3SaRg3hPSSDN9eB9xQQY7zQ2oZM/n4KFmXCLBcLyBFdvZldyglJ0xXwx2RSfaujBMJFl7zQfF7LiaoGqOPBBA0KmPxBDNo8VHSDaMTAxtNCYvIachYLxCL6azL9Gw=='

In [41]:
# Alice cannot decrypt her own message: she encrypted with BOB's public key,
# and only Bob's private key inverts it. This cell is SUPPOSED to fail.
try:
    plaintext = private_key_for_alice.decrypt(
         base64.b64decode(message_from_alice),
         padding.OAEP(
             mgf=padding.MGF1(algorithm=hashes.SHA256()),
             algorithm=hashes.SHA256(),
             label=None
         )
     )
except ValueError as exc:
    # The library deliberately gives a vague error. Distinguishing "bad padding" from
    # "bad key" is exactly the leak that enables Bleichenbacher's attack on PKCS#1 v1.5.
    print("Decryption failed as expected:", type(exc).__name__, "-", exc)

Decryption failed as expected: ValueError - Decryption failed


In [42]:
# Bob's private key inverts the operation and returns the original bytes exactly.
plaintext = private_key_for_bob.decrypt(
     base64.b64decode(message_from_alice),
     padding.OAEP(                       # padding parameters must match the sender's EXACTLY
         mgf=padding.MGF1(algorithm=hashes.SHA256()),
         algorithm=hashes.SHA256(),
         label=None
     )
 )
plaintext

b'We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard;'

## There's more to it: RSA cannot encrypt real data

RSA operates on numbers smaller than the modulus, so the message must fit inside one
modulus. With OAEP-SHA256 and a 2048-bit key that ceiling is
$k - 2 h_{Len} - 2 = 256 - 64 - 2 = \mathbf{190}$ bytes -- about two sentences.

Watch what happens when we exceed it.

In [43]:
# Extend the message past the 190-byte OAEP limit.
plain_text = plaintext + b' because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one we intend to win, and the others, too.'
print(len(plain_text), "bytes -- well over the 190-byte limit")
plain_text

353 bytes -- well over the 190-byte limit


b'We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard; because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one we intend to win, and the others, too.'

In [44]:
# This cell is SUPPOSED to fail: the data is too long for the key.
# There is no "chunk it into blocks" fix -- that is textbook RSA with extra steps,
# and it reintroduces every weakness OAEP was added to remove.
try:
    cipher_text_from_alice = encryption_key.encrypt(
         plain_text,
         padding.OAEP(
             mgf=padding.MGF1(algorithm=hashes.SHA256()),
             algorithm=hashes.SHA256(),
             label=None
         )
     )
except ValueError as exc:
    print("Encryption refused:", exc)
    print("\nThe fix is not a bigger key. The fix is envelope encryption -->")

Encryption refused: Encryption failed

The fix is not a bigger key. The fix is envelope encryption -->


# Envelope Encryption

## The problem, in one sentence

RSA cannot encrypt your data, because your data is bigger than 190 bytes.

That is not a defect to work around. RSA was never meant to carry a payload; it is a way to
move a *key*. It is also about a thousand times slower per byte than a symmetric cipher, so
even if the size limit vanished you would not want to use it on a large file.

## The idea

Use each tool for the job it is good at:

* **A symmetric cipher** encrypts the data. Fast, and no length limit.
* **RSA** encrypts the symmetric key. Slow, but the key is only a few dozen bytes.

Then send both parts together. The name comes from the physical picture: the message is a
letter, the symmetric key is sealed in an envelope that only the recipient can open, and the
two travel together.

## Two keys, two jobs

The two keys have standard names, and keeping them straight is most of understanding this
section:

| Name | What it is | Lifetime | Who can use it |
|---|---|---|---|
| **Data Encryption Key (DEK)** | A fresh random symmetric key | **One message.** Generated, used, discarded. | Anyone who can decrypt it |
| **Key Encryption Key (KEK)** | The recipient's long-term RSA key pair | Years | Only the holder of the private half |

The DEK protects the data. The KEK protects the DEK. Nothing else in this section is
complicated.

## The four steps

**Sending** (Alice has Bob's public key, and nothing else):

1. Generate a brand-new **DEK** -- a random symmetric key for this one message.
2. Encrypt the **message** with the DEK. Fast, any length.
3. Encrypt the **DEK** with Bob's **public key**. Slow, but it is only a few dozen bytes.
4. Send the encrypted DEK and the encrypted message together.

**Receiving** (Bob has his private key):

1. Decrypt the **DEK** with his private key -- open the envelope.
2. Decrypt the **message** with the recovered DEK -- read the letter.

<img src="Asymmetric Encryption Primitives - Envelope Encryption.svg"/>

## You already rely on this

This is not an academic construction. It is how essentially all encrypted data moves or
rests:

| System | The DEK | The KEK |
|---|---|---|
| **Transport Layer Security (TLS)** | The per-connection session key | The server's certificate key or an agreed key |
| **Encrypted email** (S/MIME, PGP) | A per-message content key | Each recipient's public key |
| **Full-disk encryption** (BitLocker, LUKS, FileVault) | The volume key that actually encrypts sectors | A key derived from your password, or held in a TPM |
| **Cloud key management** (AWS KMS, Azure Key Vault) | A data key returned to your application | A master key that never leaves the service |
| **Encrypted backups and archives** | A key per archive | The operator's or escrow key |

Full-disk encryption is the clearest case of why the indirection is worth it: changing your
password re-wraps the volume key, which takes milliseconds. Without the indirection you
would have to re-encrypt the entire disk.

We use the Fernet recipe here for the symmetric half because it is one line
(<https://cryptography.io/en/latest/fernet/>). For new production work, AES in
Galois/Counter Mode (AES-GCM) is the better symmetric choice: it is a single FIPS-approved
primitive rather than two, and it can authenticate a plaintext header.

> **Standards trace.** Key-transport schemes built this way are specified in
> **NIST [SP 800-56B Rev. 2](https://csrc.nist.gov/pubs/sp/800/56/b/r2/final)**
> (RSA-based key establishment). The modern, standardized version of this whole pattern is
> **Hybrid Public Key Encryption (HPKE)**, [RFC 9180](https://www.rfc-editor.org/rfc/rfc9180),
> which packages the key establishment, the key derivation and the authenticated encryption
> into a single interface.

In [45]:
# The long message from above that RSA alone could not handle.
len(plain_text)

353

In [ ]:
# STEP 1 of 4 -- generate the Data Encryption Key (DEK).
# This is a brand-new random symmetric key, used for this one message and then discarded.
from cryptography.fernet import Fernet
symmetric_key = Fernet.generate_key()      # <- this is the DEK

# Reusing a DEK across messages defeats the whole design: two messages under one key means
# compromising that key exposes both. Generate one per operation, every time.
symmetric_key

In [ ]:
# STEP 2 of 4 -- encrypt the MESSAGE with the DEK.
# Symmetric encryption has no length limit and runs at hundreds of megabytes per second.
f = Fernet(symmetric_key)
cipher_text = f.encrypt(plain_text)
print(len(cipher_text), "bytes of token for", len(plain_text), "bytes of plaintext")
cipher_text

In [ ]:
# STEP 3 of 4 -- encrypt the DEK with the recipient's public key (the KEK).
# The DEK is 44 bytes, comfortably under the 190-byte OAEP limit we hit earlier.
# This single RSA operation is the only slow step, no matter how large the message was.
protected_key_from_alice = encryption_key.encrypt(
     symmetric_key,
     padding.OAEP(
         mgf=padding.MGF1(algorithm=hashes.SHA256()),
         algorithm=hashes.SHA256(),
         label=None
     )
 )
protected_key_from_alice

In [ ]:
# A real message needs a defined wire format so the receiver can find each field.
# JSON is verbose but self-describing and easy to debug, which is why web APIs use it.
# Where every byte counts -- a small embedded frame, a high-rate log -- you would define
# a packed binary layout instead. The cryptography does not change either way.
import json

In [ ]:
# STEP 4 of 4 -- pack both parts into one message.
# JSON holds text, not bytes, so every binary field must be base64-encoded first.
# (The Fernet token is already base64, so it only needs an ASCII decode.)
# 'protected_key' is the encrypted DEK; 'cipher_text' is the encrypted message.
message_for_bob = {
    'protected_key': base64.b64encode(protected_key_from_alice).decode('utf-8'),
    'cipher_text': cipher_text.decode('utf-8')
}
message_for_bob

In [51]:
# Still a Python object living in this process's memory.
type(message_for_bob)

dict

In [52]:
# Serialization turns the object into a byte stream that can cross a network.
json_for_bob = json.dumps(message_for_bob, indent=4)
print(json_for_bob)

{
    "protected_key": "AEmkIxpCBlRrD5ZNGwpGOQrdXZwVZ5Htxt7lBTZAmyObWKMWHC7oIvRBQU9x7d6lg9q7lkTpZ14CU/11bMvcdUIdQdNe7gsID4Zt1jSeUUZIVCW30qrgCALhsHJyHaWffoZpUhkokGH4ciCkmDTk3JjBcikiDo3m650GIaCKBeRv4QCdGG107JkY0w7TXdt9hDG2CeBsqFeM6l2mCROFeEKtlNaNBERJMVHhQLGvhzgqzhjwYmgDsxZdzGkZQWRY1nASIQ1WNKD+K8CcIPnTcwx1LAnOjYmkzsPZJvgdf5Z688JcWQUK1wyJNIFx/9hx4tc7aaJS2FGJgBIj2wbQpg==",
    "cipher_text": "gAAAAABqoIxlNabbEh-vgMpRWa0UemLoRZoI-7n1MULB7r7jFwK_w_9OvMVEmyL7yQCwbYkOXbtdHKoWoAgm6suNPd2ZA2FIgUTBhwgMCex3NqewdttEtjndH4nUTVYGiroath61vY_Zdgg1kesumGCcbXfkFHqa0p6ilsfaa6YUCjpf3LfC3K1HFD4s_rtQXoK2AZJ-xMv76N-Ah0cU-EtzPxJJt5X2luqvlxMTIEv7PkFkXRYM8HP4WD7jIHsvVPnmWO8dvMQY2PLw2CeCf2FPdxb-FGhr0OYP2wTDr_sqNH_orpAsNIYP6IYRMz4tJp-VlBCbK-S_SZXRefStNr209kABboCjIq9d_C0cCXbPevUukBKyHiWTFDNlJ3fz_R1-nbAVyuXpU0ms3LKT-KN9RGA05RBC18J6W_zCUQwjEV70MtXhLjCTwc58ORzjKztp9QjNVX5TvxC1WXi022vqbFVU3YthAGQU9CTa0wsjsGGoBB1DTmNSaMqYaRcAXZ1PvOKruQ9tbziIjivHQJKkpiJlrxUQOytauJJ4UglpkNKIvygkrwE="
}


In [53]:
# Now it is a str: safe to put in an HTTP body, an MQTT payload, or a file.
type(json_for_bob)

str

### Pretend a message went across the internet....


In [54]:
# Bob parses the message. Note that parsing untrusted input is itself an attack
# surface -- always bound the size and validate the fields before using them.
message_from_alice = json.loads(json_for_bob)
message_from_alice

{'protected_key': 'AEmkIxpCBlRrD5ZNGwpGOQrdXZwVZ5Htxt7lBTZAmyObWKMWHC7oIvRBQU9x7d6lg9q7lkTpZ14CU/11bMvcdUIdQdNe7gsID4Zt1jSeUUZIVCW30qrgCALhsHJyHaWffoZpUhkokGH4ciCkmDTk3JjBcikiDo3m650GIaCKBeRv4QCdGG107JkY0w7TXdt9hDG2CeBsqFeM6l2mCROFeEKtlNaNBERJMVHhQLGvhzgqzhjwYmgDsxZdzGkZQWRY1nASIQ1WNKD+K8CcIPnTcwx1LAnOjYmkzsPZJvgdf5Z688JcWQUK1wyJNIFx/9hx4tc7aaJS2FGJgBIj2wbQpg==',
 'cipher_text': 'gAAAAABqoIxlNabbEh-vgMpRWa0UemLoRZoI-7n1MULB7r7jFwK_w_9OvMVEmyL7yQCwbYkOXbtdHKoWoAgm6suNPd2ZA2FIgUTBhwgMCex3NqewdttEtjndH4nUTVYGiroath61vY_Zdgg1kesumGCcbXfkFHqa0p6ilsfaa6YUCjpf3LfC3K1HFD4s_rtQXoK2AZJ-xMv76N-Ah0cU-EtzPxJJt5X2luqvlxMTIEv7PkFkXRYM8HP4WD7jIHsvVPnmWO8dvMQY2PLw2CeCf2FPdxb-FGhr0OYP2wTDr_sqNH_orpAsNIYP6IYRMz4tJp-VlBCbK-S_SZXRefStNr209kABboCjIq9d_C0cCXbPevUukBKyHiWTFDNlJ3fz_R1-nbAVyuXpU0ms3LKT-KN9RGA05RBC18J6W_zCUQwjEV70MtXhLjCTwc58ORzjKztp9QjNVX5TvxC1WXi022vqbFVU3YthAGQU9CTa0wsjsGGoBB1DTmNSaMqYaRcAXZ1PvOKruQ9tbziIjivHQJKkpiJlrxUQOytauJJ4UglpkNKIvygkrwE='}

In [55]:
# json.loads gives back a dictionary with the two fields Alice defined.
type(message_from_alice)

dict

In [ ]:
# RECEIVING, STEP 1 -- pull out the encrypted DEK. Still unreadable at this point.
key_bytes = base64.b64decode(message_from_alice['protected_key'])
print(key_bytes)

In [ ]:
# RECEIVING, STEP 2 -- open the envelope: decrypt the DEK with the private key.
# Only Bob can do this. One RSA operation, regardless of how big the message was.
key_for_bob = private_key_for_bob.decrypt(
     key_bytes,
     padding.OAEP(
         mgf=padding.MGF1(algorithm=hashes.SHA256()),
         algorithm=hashes.SHA256(),
         label=None
     )
 )
# This should be byte-identical to the symmetric_key Alice generated.
print("recovered key matches Alice's:", key_for_bob == symmetric_key)
key_for_bob

In [ ]:
# RECEIVING, STEP 3 -- read the letter: decrypt the message with the recovered DEK.
# Fernet verifies its authentication tag first, so a modified cipher_text raises
# InvalidToken here rather than returning corrupted plaintext.
f = Fernet(key_for_bob)
plaintext_for_bob = f.decrypt(message_from_alice['cipher_text'].encode('ascii'))
plaintext_for_bob

In [59]:
# A hard-coded key/token pair, so this cell works even if the cells above were skipped.
f1 = Fernet(b'exNKLPQC18asE5mPBId7610ke6VzdoG-ScVAi4zOgfE=')
f1.decrypt(b'gAAAAABhWy14JJVVczjJJN5XiYksAcRUKO_iMfgNMhtAroORPFqtkDDckxiy5fXrJfrY1bBBqSf3TCy_Cvmg8Wv8AwPpwDfo_htZ6NCcF55Lr_VSD0D5EgOXLeg8fFzeVZ_AiQMoha6-TQyRu1WusP5zNAgDR0ToFQ==')

b'Hope to join the CyberTruck Challenge next year !'

We are no longer limited by RSA's size constraint. Only the 44-byte Data Encryption Key
(DEK) passes through the slow asymmetric operation; the message itself moves at AES speed,
however large it is.

Three properties are worth naming, because they are what make this pattern scale:

* **One recipient or many.** Encrypt the same DEK once per recipient public key and attach
  all the wrapped copies. The payload is stored exactly once. This is how an encrypted
  email reaches five people, and how a shared cloud object is readable by a whole team.
* **Cheap re-keying and revocation.** Re-wrap the DEK for the remaining recipients. You
  never re-encrypt the data. This is also why changing a full-disk-encryption password is
  instant rather than an overnight job.
* **Nothing secret sits on the sender.** Alice needed only Bob's *public* key. If her
  machine is compromised afterwards, there is no stored secret to steal.

What this does **not** give you is authenticity. Bob's public key is public, so *anyone*
can send him a perfectly valid envelope and put Alice's name on it. Closing that gap needs
a digital signature, which is a different primitive from encryption.

### The modern form of this pattern

Hand-assembling "RSA-wrap a Fernet key inside JSON" is a good teaching exercise and a bad
production habit: the field order, the padding parameters, and the binding between the
wrapped key and the ciphertext are all yours to get wrong.

**Hybrid Public Key Encryption (HPKE)**, [RFC 9180](https://www.rfc-editor.org/rfc/rfc9180),
standardizes exactly this construction. It names three pieces:

* a **Key Encapsulation Mechanism (KEM)** to establish a shared secret with the recipient's
  public key -- the job RSA-OAEP did above;
* a **Key Derivation Function (KDF)** to expand that secret into usable key material;
* an **Authenticated Encryption with Associated Data (AEAD)** cipher to protect the payload.

HPKE is what Transport Layer Security (TLS) 1.3 Encrypted Client Hello and modern secure
messaging use. Recent versions of `cryptography` expose it, including **hybrid
post-quantum** suites that run a lattice-based Key Encapsulation Mechanism (ML-KEM-768)
alongside the classical X25519, so a recording captured today cannot be decrypted by a
future quantum computer -- the "harvest now, decrypt later" problem.

The cell below is optional and will simply report if your version is too old.

In [60]:
# Optional: the standardized replacement for the hand-rolled envelope above.
# One call replaces "generate DEK -> encrypt payload -> RSA-wrap DEK -> pack JSON".
try:
    from cryptography.hazmat.primitives import hpke
    from cryptography.hazmat.primitives.asymmetric import x25519

    bob_hpke = x25519.X25519PrivateKey.generate()      # the recipient's long-term key
    suite = hpke.Suite(hpke.KEM.X25519,                # key encapsulation mechanism
                       hpke.KDF.HKDF_SHA256,           # key derivation
                       hpke.AEAD.AES_256_GCM)          # payload protection

    sealed = suite.encrypt(b"unlock diagnostic session", bob_hpke.public_key())
    print("HPKE sealed:", len(sealed), "bytes  (encapsulated key + ciphertext + tag)")
    print("HPKE opened:", suite.decrypt(sealed, bob_hpke))

    # Post-quantum hybrid suites are named here too; availability varies by build.
    print("\nPQC hybrid KEMs defined in this build:",
          [n for n in dir(hpke.KEM) if n.startswith("MLKEM")])
except Exception as exc:
    print("HPKE not available in this build:", type(exc).__name__, exc)
    print("Upgrade with:  pip install --upgrade cryptography")

HPKE sealed: 73 bytes  (encapsulated key + ciphertext + tag)
HPKE opened: b'unlock diagnostic session'

PQC hybrid KEMs defined in this build: ['MLKEM1024', 'MLKEM1024_P384', 'MLKEM768', 'MLKEM768_X25519']


> **Standards trace -- post-quantum.** The KEM names above are **ML-KEM** ([FIPS 203](https://csrc.nist.gov/pubs/fips/203/final)),
> the standardized version of CRYSTALS-Kyber, paired with X25519 so the result is no
> weaker than the classical scheme. The draft **[NIST IR 8547](https://csrc.nist.gov/pubs/ir/8547/ipd)** proposes deprecating RSA and
> elliptic-curve key establishment after **2030** and disallowing them after **2035**. For a vehicle
> program that is a live design constraint, not a research topic: an ECU flashed in 2028
> with a 15-year service life will still be in the field when RSA is disallowed.
> The relevant question for a design review is not "is RSA broken?" but "can this ECU's
> keys and algorithms be replaced in the field?" -- that is crypto-agility.

---
## Try It Yourself #2: Specify an envelope-encryption function

You built this by hand a few cells ago, so you know what it must contain: a fresh data
encryption key per message, an AEAD for the payload, OAEP for the key wrap, and a defined
wire format. Writing that as a specification is more durable than remembering the API.

### How these exercises work

You now know enough to *specify* this code precisely, which is a more durable skill than
remembering an application programming interface (API). A language model will write the
code either way; what decides whether the result is correct is how completely you described
it, and whether you had a test ready before you looked at the answer.

A prompt worth writing names five things:

| | What to state | Why |
|---|---|---|
| 1 | Library **and version** | Otherwise you get a different library each time |
| 2 | Exact primitive and **parameters** | Algorithm, mode, key length, nonce policy, padding |
| 3 | The **interface** | Function name, argument types, return type |
| 4 | What must **not** happen | No swallowed exceptions, no hard-coded keys, no deprecated modes |
| 5 | How it will be **verified** | Name the test vector or property up front |

Item 5 is the one people skip, and it is the one that does the most work.

**If the acceptance test below fails, fix the prompt, not the code.** Patching the output
teaches nothing that transfers. Rewriting the specification until a cold model produces
passing code on the first try is the thing worth practising, and it is the same skill as
writing a requirement for a supplier.

### The weak prompt

> Write a function that encrypts a long message with RSA.

A model will answer that. It will choose the library, the mode, the key length and
the error behavior for you, and you will have no basis for checking any of it.

### Starting point -- edit this, then hand it to your assistant

```
Using the Python `cryptography` library (version 42 or later), write two functions:

    wrap(recipient_public_pem: bytes, plaintext: bytes) -> str
    unwrap(recipient_private_pem: bytes, envelope_json: str) -> bytes

Requirements:
- Generate a fresh 32-byte data encryption key with os.urandom for EVERY call to wrap().
- Encrypt the payload with AES-256-GCM (SP 800-38D) using a fresh 12-byte nonce.
- Wrap the data encryption key with RSA-OAEP using MGF1-SHA256 and SHA-256
  (RFC 8017 Sec. 7.1). Do not use PKCS#1 v1.5 padding.
- Return a JSON string with exactly these keys, all base64-encoded:
  "protected_key", "nonce", "cipher_text".
- unwrap() lets cryptography.exceptions.InvalidTag propagate on a bad tag.
  Do not catch or suppress exceptions. Do not hard-code keys.
- Load PEM keys with serialization.load_pem_public_key / load_pem_private_key.
```

### Read the answer before you run it

* Is the data encryption key **generated inside** `wrap()`, or passed in and reused?
* Which **padding** did it choose for the RSA step? `PKCS1v15` is a wrong answer.
* Is the payload cipher an **AEAD**, or plain CBC with no integrity?
* Does `unwrap()` **raise** on a bad tag, or return `None` and let the caller continue?

Paste the generated code into the next cell and run it. **If the acceptance test
fails, tighten the prompt and regenerate** rather than editing the output by hand.

In [61]:
# Paste the generated wrap()/unwrap() below this line, then run the cell.
# ===========================================================================


# ===========================================================================
# Acceptance test -- do not edit. It builds its own keys, so it is self-contained.
import inspect, json as _json, base64 as _b64
from cryptography.hazmat.primitives.asymmetric import rsa as _rsa
from cryptography.exceptions import InvalidTag as _IT

_results = None
try:
    _key = _rsa.generate_private_key(public_exponent=65537, key_size=2048)
    _priv_pem = _key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption())
    _pub_pem = _key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo)
    _msg = b"firmware image 4921-778 " * 100

    _e1, _e2 = wrap(_pub_pem, _msg), wrap(_pub_pem, _msg)
    _d1, _d2 = _json.loads(_e1), _json.loads(_e2)
    _src = inspect.getsource(wrap) + inspect.getsource(unwrap)

    _results = {
        "round trip works":        unwrap(_priv_pem, _e1) == _msg,
        "json has 3 fields":       set(_d1) == {"protected_key", "nonce", "cipher_text"},
        "DEK is fresh per call":   _d1["protected_key"] != _d2["protected_key"],
        "nonce is fresh per call": _d1["nonce"] != _d2["nonce"],
        "nonce is 12 bytes":       len(_b64.b64decode(_d1["nonce"])) == 12,
        "wrapped key is 256 B":    len(_b64.b64decode(_d1["protected_key"])) == 256,
        "not PKCS#1 v1.5":         "PKCS1v15" not in _src,
        "payload is an AEAD":      len(_b64.b64decode(_d1["cipher_text"])) == len(_msg) + 16,
        "no bare except":          "except:" not in _src,
    }
    _ct = bytearray(_b64.b64decode(_d1["cipher_text"])); _ct[-1] ^= 0x01
    _bad = dict(_d1); _bad["cipher_text"] = _b64.b64encode(bytes(_ct)).decode()
    try:
        unwrap(_priv_pem, _json.dumps(_bad)); _results["tampering rejected"] = False
    except _IT:
        _results["tampering rejected"] = True
except NameError:
    pass

# ---------------------------------------------------------------------------
# Report. Nothing here raises, so "Run All" still works on an untouched notebook.
if _results is None:
    print("Paste the generated code above, then re-run this cell.")
else:
    for _name, _ok in _results.items():
        print(("  [OK] " if _ok else "  [--] ") + _name)
    _p = sum(_results.values())
    print(f"\n{_p} of {len(_results)} checks passed.",
          "Prompt accepted." if _p == len(_results) else "Tighten the prompt and regenerate.")

Paste the generated code above, then re-run this cell.


## Class Exercise

Send me an encrypted form of the Star Spangled Banner (or some other meaningful text)
using the envelope pattern you just built.

Specification:

1. **RSA 2048-bit** with **OAEP-SHA256** padding for the key transport.
2. The message is a **JSON object** with exactly two fields:
   * `protected_key` -- base64 of the RSA-encrypted Fernet key
   * `cipher_text` -- the Fernet token
3. Use my public key, below, as the recipient.

Think about what this exercise does *not* prove: I will be able to read your message, but
I will have no idea which of you sent it. Anyone who has my public key can produce a valid
envelope. Closing that gap requires a digital signature, not encryption.

In [62]:
# Triple-quoted bytes keep the line structure by embedding real newline characters.
text_to_send = b'''O say can you see, by the dawn's early light,
What so proudly we hailed at the twilight's last gleaming,
Whose broad stripes and bright stars through the perilous fight,
O'er the ramparts we watched, were so gallantly streaming?
And the rocket's red glare, the bombs bursting in air,
Gave proof through the night that our flag was still there;
O say does that star-spangled banner yet wave
O'er the land of the free and the home of the brave?'''
print(len(text_to_send), "bytes -- far more than RSA alone can carry")
text_to_send

442 bytes -- far more than RSA alone can carry


b"O say can you see, by the dawn's early light,\nWhat so proudly we hailed at the twilight's last gleaming,\nWhose broad stripes and bright stars through the perilous fight,\nO'er the ramparts we watched, were so gallantly streaming?\nAnd the rocket's red glare, the bombs bursting in air,\nGave proof through the night that our flag was still there;\nO say does that star-spangled banner yet wave\nO'er the land of the free and the home of the brave?"

In [63]:
# Load a private key that was generated once and saved, rather than made on the fly.
# password=None means the PEM is unencrypted -- acceptable only because this key is a demo.
try:
    with open('Daily_Private_RSA2048_key.pem','rb') as pem:
        private_key_for_daily = serialization.load_pem_private_key(pem.read(),password=None)
    print(private_key_for_daily)
except FileNotFoundError:
    private_key_for_daily = None
    print("Daily_Private_RSA2048_key.pem not found -- students only need the PUBLIC key below.")

In [64]:
# The public half is what gets published; the private half stays on my machine.
public_key_for_daily = private_key_for_daily.public_key() if private_key_for_daily else None
public_key_for_daily

In [65]:
# Serialize and save the public key so it can be handed out or committed to the repo.
if public_key_for_daily is not None:
    public_pem_key_for_daily = public_key_for_daily.public_bytes(
           encoding=serialization.Encoding.PEM,
           format=serialization.PublicFormat.SubjectPublicKeyInfo
    )
    print(public_pem_key_for_daily.decode('ascii'))
    with open('Daily_Public_RSA2048_key.pem','wb') as f:
        f.write(public_pem_key_for_daily)

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1bHZs7RxSNTk+Z1MMkHE
v7F7WK5oxLmJ9HypDyagbF4csmwCqsnhMwqJ9vEi3zmlE3VtjfrjpNSJSSvr1RDV
mxh7yz7z+sKvH+JBccMxmFS7/IrKZpNLJPnSY4JlrrCVKYhGwcx0z+kr0Xd4fi97
NVH7xSZaVTXJ+SC19j4EN/gb8nWcYk6umBJmVF688RdOeHQ6ZE3hLbUhKW48oDu1
u8YyRWIHNYyxZXz7G7ojuosd69e7bkO2GR0gAmQpZhXurxD5EGJLYWKvNFYcWPux
YJvgjlmBJCcGz4lKSJcdNzZfSg2YLqopKLcKmNSR9NmywpXIMu0S3wUAWJ7SgGMm
XQIDAQAB
-----END PUBLIC KEY-----



Follow the envelope-encryption steps above and produce a message I can run through
`decrypt_class_message()`. The `encrypt_class_message()` function below is a complete
worked reference -- read it line by line and make sure you can say what each step is for
before you use it.

In [66]:
# Everything needed to build one envelope message, in one place.
import json
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

def encrypt_class_message(plain_text, public_pem_key):
    '''Wrap a fresh Fernet key with an RSA public key and return a JSON envelope.'''
    # 1. Parse the recipient's PEM text into a key object.
    public_key = serialization.load_pem_public_key(public_pem_key.encode('utf-8'))
    print(public_key)

    # 2. Fresh symmetric key for THIS message only (the data encryption key).
    unique_key = Fernet.generate_key()
    print(unique_key)

    # 3. Bulk-encrypt the payload -- fast, and no length limit.
    f = Fernet(unique_key)
    cipher_text = f.encrypt(plain_text.encode('ascii'))
    print(cipher_text)

    # 4. Protect the small key with the recipient's public key.
    protected_key = public_key.encrypt(
         unique_key,
         padding.OAEP(
             mgf=padding.MGF1(algorithm=hashes.SHA256()),
             algorithm=hashes.SHA256(),
             label=None
         )
     )

    # 5. Pack both parts into a transportable, text-safe structure.
    message_dict = {
        'protected_key': base64.b64encode(protected_key).decode('utf-8'),
        'cipher_text': cipher_text.decode('utf-8')
    }
    return json.dumps(message_dict)

In [67]:
# My published RSA-2048 public key. Copy it; there is nothing secret in it.
daily_pub_pem = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1bHZs7RxSNTk+Z1MMkHE
v7F7WK5oxLmJ9HypDyagbF4csmwCqsnhMwqJ9vEi3zmlE3VtjfrjpNSJSSvr1RDV
mxh7yz7z+sKvH+JBccMxmFS7/IrKZpNLJPnSY4JlrrCVKYhGwcx0z+kr0Xd4fi97
NVH7xSZaVTXJ+SC19j4EN/gb8nWcYk6umBJmVF688RdOeHQ6ZE3hLbUhKW48oDu1
u8YyRWIHNYyxZXz7G7ojuosd69e7bkO2GR0gAmQpZhXurxD5EGJLYWKvNFYcWPux
YJvgjlmBJCcGz4lKSJcdNzZfSg2YLqopKLcKmNSR9NmywpXIMu0S3wUAWJ7SgGMm
XQIDAQAB
-----END PUBLIC KEY-----"""

# Try it with a short message first, then with the anthem above.
encrypt_class_message("Hello!", daily_pub_pem)

b'EiqgcFij5yCPCGkk_v5zONYIHSsxeDZsf3MN9nBSpJ0='
b'gAAAAABqoIyOc56Pww_Nu5psOJVVgp-u2J0bKg802PSMXYHR1m97XEF0m3I2UhUd4WicBwdvxxxeh4CbvelwTGEu1SW-CqPx_A=='


'{"protected_key": "0gw2ErAgEF8072ErYx9Z2F20/wFVId2t4byckZaqHv0RYuh9TSHRlYLMrnM3XrRr6wkhfpRmxI0E+9qX9j+ua769TpyoqNcW0FZXaDhryUUVif4J3h6cWsW8pb8MMO0x2A6hNiqh6h97pLtqQU8jMC9NhgqEFpHbHDweVtOxCTYtNfeJ8x4dp6CrjFXUeIRxjRCv0pdwJBCC48Ac0jaqUvATGiRS2xRMJebyQzIWPR8ZrLgUweI2BtXcSD/13PZ8Nl/rstz+fOxBt5gm1YTURB9LMIEjfEpq96P2WJe+qMikFYBUB6mlRvUP4XWroTtLHptzNVFlBoUp0M6ppeeF0Q==", "cipher_text": "gAAAAABqoIyOc56Pww_Nu5psOJVVgp-u2J0bKg802PSMXYHR1m97XEF0m3I2UhUd4WicBwdvxxxeh4CbvelwTGEu1SW-CqPx_A=="}'

In [68]:
# YOUR TURN. This is the inverse of encrypt_class_message().
# Steps: parse the JSON -> base64-decode protected_key -> RSA-decrypt it with the
# private key -> build a Fernet object from the recovered key -> decrypt cipher_text.
def decrypt_class_message(json_from_student, private_pem_key):
    message_from_student = json.loads(json_from_student)
    key_bytes = base64.b64decode(message_from_student['protected_key'])

    ##
    ## Fill in this part for the exercise:
    ##   private_key = serialization.load_pem_private_key(private_pem_key, password=None)
    ##   unique_key  = private_key.decrypt(key_bytes, padding.OAEP(...))
    ##   f           = Fernet(unique_key)
    ##   message_bytes = message_from_student['cipher_text'].encode('ascii')
    ##
    raise NotImplementedError("complete the four lines above")

    plaintext_message = f.decrypt(message_bytes)
    return plaintext_message

In [69]:
# The instructor's private key. Students will not have this file, which is the point:
# they can encrypt TO me without being able to decrypt anyone else's submission.
try:
    with open('Daily_Private_RSA2048_key.pem','rb') as pem:
        private_pem_key = pem.read()
    print("private key loaded:", len(private_pem_key), "bytes of PEM")
except FileNotFoundError:
    private_pem_key = None
    print("Daily_Private_RSA2048_key.pem not present -- expected on a student machine.")

private key loaded: 1704 bytes of PEM


In [70]:
# Paste your JSON envelope into `student` and run. Until decrypt_class_message()
# is completed above, this raises NotImplementedError -- that is your assignment.
jeremy = '{"protected_key": "CkWAuKAXMi+BXF/cHRts4VDnp9437JGZCaga/PKFgCglA6q87KxLjS03Xxpa1rwAjP4dyx9lzFfSlyEOdhh45diGXBA2fN7tezJ2W/WTDbv2Sg7K9Bfs0BsXA3uEpuE+5Nj2fPIOC2RYWE1VMhg37OcsOO9xbOpuDzcRACGzWFtCT4R7l5+nLO9u3y9I4UdGYFM4njHriiUcXdFiJD8TbczVRAjt2bi2Pi5RX3tzmhrWlFVyQFELvcCKHv93tfvw7bTzA4QCMyVB4nmT8dsAnqE+SM5KWoDIODEMSRDlpNQz8MCvlkK7dyjDiT9O9a1Q6kaI/qrOHPo+BXXqSgULgw==", "cipher_text": "gAAAAABhQ-8Ecam7MIfrsTrg40qPQnBlgx4ceyMVDbunVMS5D0M8YOmbslEmR7aw_WAjMgYIoNbMV2xHeHCcNxd7Ukiuo8kUIA=="}'
bob = '{"protected_key": "KEo8SI4tLYafiLuqAAsPHE3Vz54ICWXC3UrU6RYpDQf68JPT7B5re10QysECFXausqZuoBcJXjKLqVwW1Ezxk8gKBZsoytJs0PcaMOeLNV9lf1eLAmdjfdiBG8F382rA2QYb5l7q9PfWwDqSL6K7rXaZmBt1i8hZdZ1xxXhcbuFYgF1cN5kNOR7lhrnqPvtqRFi6WmXD52yMwJmyc8Fd7v0UTg5aGJu/uW1WtT6rBao0L+nAA53aGAYiTGkN5JqA+sIytMA6cslFABeTnOXhUS7sPsSYOtpOBpyiM/lPYeEQpl/SSdpBgeD1yumrvNNmLhKLbbgIyfGBvDZBR5DnBg==", "cipher_text": "gAAAAABfbeFZiMpdzgj1ef_irV8Xq1H68PpbM9AYgDJaxjY6tYkAiMa8ZvVVJGisnzcqgb0vEVo6qqB-SZTh2numILEp6jReOoHw_8ElX9iWAysKg7rFrbr_0_eFsnnPVeZonoa7p9BR6Mo9iLmzn1vMh2Hs40XUcXXF5hn_9f1QDs-jA7XkbAieReLguEt6k4TyKQSkD2tgk1iTMhvShfhLQX-Ocv_gwvjtcJlQV4u9sdzIwL06VST-YGLVSqfxTVOpdIodxPz8V6l4vIBWNMNiwrzxFloYrj8M0RCMoXITV23HKIVacFnEJa4SPI_I2tKpGMyNiUEBpBpXlK7a9PDxI_y03Cnw8gIe4TzUDdgDRhsbhdfWEYxfTcUxr8A7db48WjJvdgVlphSgT4YsesN7vbJCKHAPw1m_CJI0SXdMVRhlxfEDOauPB_UHWEEh7suqVFZ5xkJ0dIbmdHYqxnxwv0Sx6L3Zu3bGnK1IU_pl7wI4vRh8lW7R0TwJsHZZfmqIKgzgy4VPCjmIWl1bLn7M9w8IveVdu5e_Jkvq7rdfoWaQmw_gQFA1-2E6yB3Q0VTcBALnEIGtTZ1vg8cv-D3GhBdMdCNsp8IuhtY5UcGqNJjbpqDYrxfyW50bsvMnvAVLcGr51Dy-Lrz2rWqep8Fk8831OSbF6Q=="}'

student = jeremy
if private_pem_key:
    try:
        print(decrypt_class_message(student, private_pem_key))
    except NotImplementedError as exc:
        print("Not finished yet:", exc)
else:
    print("No private key on this machine -- run this cell on the instructor's copy.")

Not finished yet: complete the four lines above


---
# Notebook Summary

### What we built

| Step | Primitive | Why |
|---|---|---|
| Generate a keypair | RSA-2048, e = 65537 | Splits the key so one half can be published |
| Serialize to PEM | SubjectPublicKeyInfo | How keys actually move between systems |
| Encrypt to a public key | RSA-OAEP-SHA256 | Randomized, non-malleable; textbook RSA is neither |
| Hit the 190-byte wall | [RFC 8017](https://www.rfc-editor.org/rfc/rfc8017) Sec. 7.1.1 | RSA is key transport, not a bulk cipher |
| Envelope encryption | RSA-OAEP + Fernet | Asymmetric for the key, symmetric for the data |
| HPKE | [RFC 9180](https://www.rfc-editor.org/rfc/rfc9180) | The standardized version of that same pattern |

### Three sentences to remember

1. **A public key is not a secret, and a private key never moves.** Everything else follows
   from that split.
2. **RSA moves keys, not data.** Any design that "chunks" a large message through RSA is a
   design that has misunderstood what RSA is for.
3. **Confidentiality is not authenticity.** Anyone holding Bob's public key can send Bob a
   perfectly valid envelope and sign it "Alice."

### Standards traceability

| Element | Document |
|---|---|
| RSA key generation, sizes | [FIPS 186-5](https://csrc.nist.gov/pubs/fips/186-5/final); [SP 800-57](https://csrc.nist.gov/pubs/sp/800/57/pt1/r5/final) Pt. 1 Rev. 5 |
| OAEP padding | RFC 8017 (PKCS #1 v2.2) Sec. 7.1 |
| RSA-based key establishment | [SP 800-56B Rev. 2](https://csrc.nist.gov/pubs/sp/800/56/b/r2/final) |
| Approved sizes / retirement | [SP 800-131A Rev. 2](https://csrc.nist.gov/pubs/sp/800/131/a/r2/final) (RSA >= 2048) |
| PEM / SubjectPublicKeyInfo | [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280), [RFC 7468](https://www.rfc-editor.org/rfc/rfc7468) |
| HPKE | RFC 9180 |
| ML-KEM (post-quantum KEM) | [FIPS 203](https://csrc.nist.gov/pubs/fips/203/final); proposed timeline in draft [NIST IR 8547](https://csrc.nist.gov/pubs/ir/8547/ipd) |

### The open question

Alice sent Bob a message that only Bob can read. But Bob has no way to know it came from
Alice, and neither of them can be sure the public key they downloaded belongs to the
person they think it does. If Eve can substitute her own public key during the exchange,
she reads everything and neither party notices -- a **machine-in-the-middle** attack.

Two things are missing, and each gets its own notebook:

* **Key agreement** -- Diffie-Hellman lets two parties compute a shared secret without
  either one sending it, and ephemeral key pairs give forward secrecy: a key compromised
  tomorrow does not expose traffic recorded today.
* **Digital signatures** -- these bind a message to a private key, which is what makes
  certificates, secure boot and signed software updates possible.

### Exercises

1. Regenerate Alice's key at 4096 bits. How does the OAEP size limit change, and how much
   slower is key generation? Time it with `%%time`.
2. Encrypt the same 32-byte string twice with OAEP and once conceptually without padding.
   Explain, in one paragraph, why a deterministic ciphertext is fatal when the plaintext
   space is small (for example, a 4-digit diagnostic PIN).
3. Extend the JSON envelope so one message can be opened by *three* recipients without
   duplicating the payload. What field structure did you choose, and why?
4. An ECU built today will be serviced until 2043. Using the draft NIST IR 8547 timeline, write
   the two-line justification you would give a program manager for making its firmware crypto-agile.