import json
J1939SourceAddresses = {
    "13" : "Brakes - Drive axle #1",
    "90" : "thru 127 are reserved for future assignment by SAE",
    "43" : "On-Board Diagnostic Unit",
    "51" : "Tire Pressure Controller",
    "41" : "Retarder, Exhaust, Engine #1",
    "84" : "Cab Display #2",
    "28" : "Vehicle Navigation",
    "27" : "Aerodynamic Control",
    "15" : "Retarder - Engine",
    "16" : "Retarder - Driveline",
    "57" : "Water Pump Controller",
    "76" : "Communications Unit, Radio",
    "65" : "Information System Controller #1",
    "59" : "Transmission Display - Primary",
    "50" : "Cab Controller - Secondary",
    "82" : "Aftertreatment #1 system gas outlet",
    "70" : "Engine Valve Controller",
    "3" : "Transmission #1",
    "26" : "Alternator/Electrical Charging System",
    "47" : "Suspension - System Controller #1",
    "20" : "Suspension - Steer Axle",
    "253" : "Reserved for OEM",
    "40" : "Cab Display #1",
    "42" : "Headway Controller",
    "77" : "Steering Column Unit",
    "255" : "GLOBAL (All-Any Node)",
    "62" : "Vehicle Dynamic Stability Controller",
    "61" : "Exhaust Emission Controller",
    "85" : "Diesel Particulate Filter Controller",
    "72" : "Chassis Controller #2",
    "38" : "Virtual Terminal (in cab)",
    "89" : "Atmospheric Sensor",
    "73" : "Propulsion Battery Charger",
    "0" : "Engine #1",
    "18" : "Fuel System",
    "254" : "Null Address",
    "2" : "Turbocharger",
    "74" : "Communications Unit, Cellular",
    "8" : "Axle - Steering",
    "9" : "Axle - Drive #1",
    "86" : "Aftertreatment #2 system gas intake",
    "32" : "Tractor-Trailer Bridge #1",
    "23" : "Instrument Cluster #1",
    "83" : "Safety Restraint System",
    "1" : "Engine #2",
    "22" : "Suspension - Drive Axle #2",
    "49" : "Cab Controller - Primary",
    "5" : "Shift Console - Primary",
    "24" : "Trip Recorder",
    "48" : "Pneumatic - System Controller",
    "12" : "Brakes - Steer Axle",
    "55" : "Lighting - Operator Controls",
    "78" : "Fan Drive Controller",
    "252" : "Reserved for Experimental Use",
    "64" : "Suspension - System Controller #2",
    "81" : "Aftertreatment #1 system gas intake",
    "54" : "Seat Control #1",
    "33" : "Body Controller",
    "88" : "Safety Restraint System #S",
    "29" : "Vehicle Security",
    "30" : "Electrical System",
    "66" : "Ramp Control",
    "19" : "Steering Controller",
    "79" : "Seat Control #2",
    "4" : "Transmission #2",
    "68" : "Auxiliary Heater #1",
    "34" : "Auxiliary Valve Control or Engine Air System Valve Control",
    "10" : "Axle - Drive #2",
    "248" : "File Server / Printer",
    "249" : "Off Board Diagnostic-Service Tool #1",
    "45" : "Endurance Braking System",
    "44" : "Retarder, Exhaust, Engine #2",
    "17" : "Cruise Control",
    "71" : "Chassis Controller #1",
    "37" : "Off Vehicle Gateway",
    "75" : "Communications Unit, Satellite",
    "80" : "Parking brake controller",
    "14" : "Brakes - Drive Axle #2",
    "21" : "Suspension - Drive Axle #1",
    "56" : "Rear Axle Steering Controller #1",
    "52" : "Ignition Control Module #1",
    "87" : "Aftertreatment #2 system gas outlet",
    "36" : "Power TakeOff (Front or Secondary)",
    "69" : "Auxiliary Heater #2",
    "67" : "Clutch/Converter Unit",
    "11" : "Brakes - System Controller",
    "35" : "Hitch Control",
    "46" : "Hydraulic Pump Controller",
    "251" : "On-Board Data Logger",
    "25" : "Passenger-Operator Climate Control #1",
    "6" : "Shift Console - Secondary",
    "63" : "Oil Sensor",
    "58" : "Passenger-Operator Climate Control #2",
    "39" : "Management Computer #1",
    "250" : "Off Board Diagnostic-Service Tool #2",
    "53" : "Ignition Control Module #2",
    "60" : "Transmission Display - Secondary",
    "7" : "Power TakeOff - (Main or Rear)",
    "31" : "Starter System"
    }

print(J1939SourceAddresses)
db = {}
for k,v in J1939SourceAddresses.items():
    db[int(k)]=v

with open("SourceAddresses.json",'r') as f:
    db = json.load(f)

print(db)
with open("SourceAddresses.json",'w') as f:
    json.dump(db,f,sort_keys=True,indent=4)